<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            [
                'category_id' => 1,
                'name' => 'Cheeseburger',
                'description' => 'Burger classique avec fromage fondant et steak savoureux.',
                'image' => 'cheeseburger.jpg',
                'price' => 8.99,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Double Bacon Burger',
                'description' => 'Double steak, bacon croustillant, cheddar et sauce maison.',
                'image' => 'double_bacon_burger.jpg',
                'price' => 11.50,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Vegan Burger',
                'description' => 'Burger végétalien avec galette aux légumes et avocat.',
                'image' => 'vegan_burger.jpg',
                'price' => 9.50,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Chicken Burger',
                'description' => 'Filet de poulet croustillant, salade et sauce au yaourt.',
                'image' => 'chicken_burger.jpg',
                'price' => 9.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Spicy Burger',
                'description' => 'Burger épicé avec sauce piquante et jalapeños.',
                'image' => 'spicy_burger.jpg',
                'price' => 10.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Pizza Margherita',
                'description' => 'Sauce tomate, mozzarella et basilic frais.',
                'image' => 'pizza_margherita.jpg',
                'price' => 9.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Pizza 4 Fromages',
                'description' => 'Mozzarella, gorgonzola, parmesan et chèvre.',
                'image' => 'pizza_4_fromages.jpg',
                'price' => 11.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Pizza Pepperoni',
                'description' => 'Tranches de pepperoni et fromage fondant.',
                'image' => 'pizza_pepperoni.jpg',
                'price' => 10.50,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Pizza Végétarienne',
                'description' => 'Poivrons, champignons, olives et oignons rouges.',
                'image' => 'pizza_vegetarienne.jpg',
                'price' => 10.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Pizza Hawaïenne',
                'description' => 'Jambon, ananas et mozzarella.',
                'image' => 'pizza_hawaienne.jpg',
                'price' => 10.50,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Cup Cake Vanille',
                'description' => 'Moelleux à la vanille et glaçage crémeux.',
                'image' => 'cupcake_vanille.jpg',
                'price' => 2.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Cup Cake Chocolat',
                'description' => 'Cupcake chocolat noir avec cœur fondant.',
                'image' => 'cupcake_chocolat.jpg',
                'price' => 2.50,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Cup Cake Red Velvet',
                'description' => 'Red velvet avec glaçage cream cheese.',
                'image' => 'cupcake_red_velvet.jpg',
                'price' => 2.80,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Cup Cake Fraise',
                'description' => 'Fraise fraîche, confiture maison et chantilly.',
                'image' => 'cupcake_fraise.jpg',
                'price' => 2.60,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Cup Cake Caramel',
                'description' => 'Glaçage au caramel beurre salé et noix.',
                'image' => 'cupcake_caramel.jpg',
                'price' => 2.70,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Ramen Tonkotsu',
                'description' => 'Bouillon de porc riche et nouilles artisanales.',
                'image' => 'ramen_tonkotsu.jpg',
                'price' => 12.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Ramen Shoyu',
                'description' => 'Bouillon à base de sauce soja, œuf mariné et bambou.',
                'image' => 'ramen_shoyu.jpg',
                'price' => 11.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Ramen Miso',
                'description' => 'Bouillon miso, légumes et porc grillé.',
                'image' => 'ramen_miso.jpg',
                'price' => 11.50,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Ramen Végétarien',
                'description' => 'Bouillon légumes, tofu et champignons shiitake.',
                'image' => 'ramen_vegetarien.jpg',
                'price' => 10.50,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Ramen Epicé',
                'description' => 'Nouilles pimentées, bouillon relevé et viande marinée.',
                'image' => 'ramen_epice.jpg',
                'price' => 12.50,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

    }
}
